# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

# For a Matrix

np.array(matrix or list)

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr = np.array(my_mat)

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Generate Numpy arrays (Only Integers)

np.arange(start,stop,step)

In [16]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(2)

array([0., 0.])

np.zeros(tuple) or np.zeros((row,columns)) and np.ones()

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

# To evenly spaced numbers over an interval 

np.linspace(start,stop,number_of_points)

In [21]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# To create an identity matrix

np.eye(no_of_rows or columns)

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# To create random numbers using uniform distribution

In [24]:
np.random.rand(5)

array([0.57443332, 0.96659672, 0.73691638, 0.83952722, 0.54066544])

np.random.rand(integer)

In [27]:
np.random.rand(5,5)

array([[0.51146147, 0.86635429, 0.50771474, 0.39953273, 0.7219548 ],
       [0.13078098, 0.63866073, 0.86969692, 0.50583314, 0.94101008],
       [0.77716407, 0.51829525, 0.37525613, 0.95648088, 0.11656861],
       [0.56460148, 0.97409948, 0.17639756, 0.60230708, 0.5650752 ],
       [0.82933978, 0.17403105, 0.54467851, 0.83758507, 0.41655748]])

# To create random numbers using normal or gaussian distribution

In [28]:
np.random.randn(10)

array([-1.36743577,  0.70988595,  0.26847357, -0.05088956,  0.37468016,
       -0.04561848,  1.00966899,  0.25467027, -0.05002947, -0.15397438])

In [29]:
np.random.randn(2,2)

array([[ 0.18647208, -0.05835233],
       [ 0.64301079,  0.71282017]])

# To create random integers from a range of intervals

np.random.randint(low, high, no_of_numbers)

In [30]:
np.random.randint(0,100)

82

In [31]:
np.random.randint(0,100,10)

array([88,  6, 98,  1, 18, 58, 17, 95, 61, 48])

# Attributes of an array

In [42]:
arr = np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([ 4, 19,  8, 49, 47, 32, 13, 19, 17,  0])

# Reshape Method 

arr.reshape(new_dimensions) -> You need to completely fill up the array

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Min, Max and Index

In [37]:
ranarr.max()

49

In [38]:
ranarr.min()

0

To find the index value of the min and max value

In [39]:
ranarr.argmax()

3

In [40]:
ranarr.argmin()

9

# Shape of the array

In [48]:
np.shape(arr)

(25,)

(25,) -> Indicates that the array is 1-D

# To find the datatype of an array

In [50]:
arr.dtype

dtype('int64')

# For easy use:

In [51]:
from numpy.random import randint

In [53]:
randint(2,10)

7

# Numpy Indexing and Selection

In [54]:
arr = np.arange(0,11)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[8]

8

In [58]:
arr[2:4]

array([2, 3])

In [59]:
arr[:5]

array([0, 1, 2, 3, 4])

In [60]:
arr[7:]

array([ 7,  8,  9, 10])

To Broadcast a number to the array

In [61]:
arr[0:5] = 0

In [62]:
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [63]:
arr = np.arange(0,11)

Numpy does not to copy the value but gives the reference. So if we assign the slice to another array, changes in the slice will affect the original array

In [64]:
slice_of_arr = arr[0:6]

In [65]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [66]:
slice_of_arr[:] = 99

In [67]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# To not make changes in the original array

In [69]:
arr_copy = arr.copy()

In [70]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy[:] = 100

In [72]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [73]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a matrix

In [74]:
arr_2d = np.array([[5,10,15],[20,25,30], [35,40,45]])

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

2 Formats

In [76]:
arr_2d[0][0]

5

In [77]:
arr_2d[0,0]

5

In [82]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

# Conditional Selection

In [83]:
arr = np.arange(1,11)

In [84]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
bool_arr = arr > 5

In [87]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

If you pass the boolean array as an index to the original array, it will return the instances where the comparison was True

In [88]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

You could also use this method:

In [89]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# Numpy Operations

In [90]:
arr = np.arange(0,11)

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr + 11

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [93]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [95]:
arr / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

# Note: Warnings

In [96]:
1/0

ZeroDivisionError: division by zero

In [97]:
arr / arr

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])